### ISSUE TITLE
index error boolean series

### ISSUE THREAD

**Issue by knowledgecomputer2018** [PythonForForex/Binance-api-step-by-step-guide#1]
hi 
i have a error in line :
mask=df.date >= start_time
 df =df.loc[mask] #?????

after bigger from 1000 and lower 500 record fetch .

error:
IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

thank you very much for reply me .

**Comment by PythonForForex** [comment]
It looks like you're trying to assign a boolean value (True or False) as an index to your DataFrame.

If you're trying to filter your data use --> df[df.date >= start_time]

**Comment by knowledgecomputer2018** [comment]
hi 
thank you very much for reply but i solve it problem previous. i can not arrive to position buy/sell with your strategy percent ETH and BTC . thank you very much .god willing

**Comment by PythonForForex** [comment]
Are you using the code as is, or have you modified it?
you can try entering in a print statement under the condition where it checks for a 5% move to see if it is related to the order execution

**Comment by knowledgecomputer2018** [comment]
hi
i modifie to :
if when ticker ADA in after five candle 1 minute is rows with your %5 then
sell and reverse but nothing position in spot trade platform.
thank you very much
god willing

**Comment by knowledgecomputer2018** [comment]
hi

i have a question about how get multiple "price symbols" such as  "eth and
ada" then buy or sell bitcoin .
i work with with socket for get price and get one candle  by under link and
i want get ADA price then if eth row %5 then i sell eth if ADA row %5 the i
sell .

***@***.***_1m"


2- i have question about this strategy that why do not you use from
get_candle replace get_ticker ?


thank you very much for reply me .

god willing
