### ISSUE TITLE
solution error :IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match)."

### ISSUE THREAD

**Issue by knowledgecomputer2018** [PythonForForex/Binance-api-step-by-step-guide#10]
i have error  ;
IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).
then i put on a sleep function after mask dataframe:
 
 df = df.loc[df.date >= start_time]
sleep(0.6)

then my script is ok

thank you very much for reply me about sleep function in your script .

your script is good and your tutorials about API binance is good but please more description about your code .

good luck
god willing

**Comment by PythonForForex** [comment]
as per https://github.com/PythonForForex/Binance-api-step-by-step-guide/issues/4#issuecomment-879810576
