### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000306BFA9340>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

### ISSUE THREAD

**Issue by knowledgecomputer2018** [PythonForForex/Binance-api-step-by-step-guide#11]
hi how are you .what are you doing ?

i have a error about request to binance .i request with colab google have not error but with my windows have a error .
thank you very much for reply me .

i search very much in multiple websites but i can not solve my problem .

good luck 
god willing

**Comment by PythonForForex** [comment]
as per - https://github.com/PythonForForex/Binance-api-step-by-step-guide/issues/4#issuecomment-879810576
