### ISSUE TITLE
bsm.start_symbol_ticker_socket(callback=symbol_trade_history, symbol=symbol)

### ISSUE THREAD

**Issue by knowledgecomputer2018** [PythonForForex/Binance-api-step-by-step-guide#4]
hi this is a price good for indicator or percent strategy?? 

i do not know when closed candle then we can not detect correct macd and historgram and signal .

we split 5 ticker but i do know candle is closed or no close .

thank you very much fore reply me.

god willing

**Comment by oliver-zehentleitner** [comment]
to detect the last candle (closing) you can test:
                if data['event_time'] >= data['kline']['kline_close_time']:
If thats true, its the last candle....

**Comment by knowledgecomputer2018** [comment]
HI @oliver-zehentleitner  24hrTicker have not 'kline' feature and kline_close_time thank you very much for reply me .god willing

**Comment by oliver-zehentleitner** [comment]
If you want candles i think kline is the way to go? And if you stream kline_X then you have this fields... look at the documentation!

**Comment by knowledgecomputer2018** [comment]
HI mr oliver-zehentleitner
how are you 

i solve it problem with @kline
youtube channel "part time "
good luck 
god willing

**Comment by PythonForForex** [comment]
@knowledgecomputer2018  I'm glad to see that you found your answer. Thank you @oliver-zehentleitner  for helping!

In the future, I would ask that you only use Github to report on errors in the code posted in this repository as that is what this section is intended for. For general support and help using the API, The Binance API telegram group can be a good resource as there are many people in the group working on the same thing. - https://t.me/binance_api_english

I will go ahead and close the the seven issues you've posted here as they don't point out any errors in the code examples.
