### ISSUE TITLE
"start_symbol_ticker_socket " not match macd with tradingview

### ISSUE THREAD

**Issue by knowledgecomputer2018** [PythonForForex/Binance-api-step-by-step-guide#5]
hi how are you 

i use code and get price with start_symbol_ticker_socket and i create df then  i calculate MACD but not match with tradingview values.

god willing

**Comment by PythonForForex** [comment]
as per - https://github.com/PythonForForex/Binance-api-step-by-step-guide/issues/4#issuecomment-879810576
