### ISSUE TITLE
sleep in realtime after mask

### ISSUE THREAD

**Issue by knowledgecomputer2018** [PythonForForex/Binance-api-step-by-step-guide#6]
hi how are you 

after 10 to 15 period get price with  "start_symbol_ticker_socket" i have a error "ValueError: cannot reindex from a duplicate axis" and i set a sleep after mask df then i have late error but final after 20 to 20 period get data i have again error .but i have not row in dataframe duplicate and i have not columns in dataframe duplicate .

thank you very much for reply me .

god willing

**Comment by PythonForForex** [comment]
as per - https://github.com/PythonForForex/Binance-api-step-by-step-guide/issues/4#issuecomment-879810576
