### ISSUE TITLE
websocket vs ThreadedWebsocketManager

### ISSUE THREAD

**Issue by knowledgecomputer2018** [PythonForForex/Binance-api-step-by-step-guide#7]
hi 

what is different "websocket " or "ThreadedWebsocketManager" ?
thank you very much for more description about types websocket and use in indicators strategy or percent strategy.

or what is different prices in strategy .what is meaning of which is price such as "ticker or candle" use or suitable for indicators strategy or percent strategy.

god willing

**Comment by PythonForForex** [comment]
as per https://github.com/PythonForForex/Binance-api-step-by-step-guide/issues/4#issuecomment-879810576
