### ISSUE TITLE
IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

### ISSUE THREAD

**Issue by knowledgecomputer2018** [PythonForForex/Binance-api-step-by-step-guide#8]
hi how are you . i run your code after 510 record fetch then i have a error :

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

in the mask df:
 df = df.loc[df.date >= start_time]

i do not know why ?
because all problems is ok and correct .

thank you very much for reply me .

god willing

**Comment by PythonForForex** [comment]
as per - https://github.com/PythonForForex/Binance-api-step-by-step-guide/issues/4#issuecomment-879810576
