### ISSUE TITLE
peroid time

### ISSUE THREAD

**Issue by knowledgecomputer2018** [PythonForForex/Binance-api-step-by-step-guide#9]
hi how are you what are you doing? 

i have a question about period time slice ?

 start_time = df.date.iloc[-1] - pd.Timedelta(minutes=1)

this is a 1 minute previous . what is meaning of we have 60 records that the every record is a second get price .no meaning of one previous candle 1 minute, it is 60 price, 60 previous time(second) .

what is differ 60 price previous with 60 candle close price ?

thank you very much for reply me .
good luck
god willing

**Comment by PythonForForex** [comment]
as per - https://github.com/PythonForForex/Binance-api-step-by-step-guide/issues/4#issuecomment-879810576
